name = "cool_camera"

[[device_properties]]
name = "index"
type = "long"

[[attributes]]
name = "binning"
type = "long"
access = ["read", "write"]

[[attributes]]
name = "exposure_time"
type = "float"

[[commands]]
name = "record"
return_type = "void"
parameter_type = "void"

[[commands]]
name = "square"
return_type = "long"
parameter_type = "long"

[[commands]]
name = "report"
return_type = "float"
parameter_type = "void"

[[commands]]
name = "act"
return_type = "void"
parameter_type = "float"
